### ISSUE TITLE
Push this project upstream

### ISSUE THREAD

**Issue by bgruening** [dpryan79/HTCondor-galaxy#1]
Talking to a friend in Norway he was wondering why this is not part of the main image.

**Comment by dpryan79** [comment]
Any/all of it can be incorporated. I assumed that having slurm already was sufficient as an example for expansion, which is all that this is.

Having said that, we're using slurm now, so I don't have a way to test things anymore.

**Comment by abdulrahmanazab** [comment]
@dpryan79 Ok I'm his friend from Norway :)
The reason why I'm interested in Condor is that it supports docker (docker universe) while slurm doesn't, so one would need to provide this support manually. We are interested in submitting docker jobs from galaxy to a HPC cluster.

For testing things, if you are interested, we have a OpenStack research cloud in Finland, cPouta. I have a quota there and we could create a 15 nodes HTCondor cluster with docker Galaxy on the top.

**Comment by dpryan79** [comment]
Cool, sounds interesting. What's the simplest way to proceed with this? I could try to make a PR against @bgruening's docker-galaxy-stable repo, but I have a feeling that it'd be better for @abdulrahmanazab to play around with this or a fork of it.

**Comment by bgruening** [comment]
If you do a PR and @abdulrahmanazab tests this branch? I would also create a image just for this PR, branch? I would be also fine to accept the PR on dev as soon as it does not break the container, travis will tell us.

Than @abdulrahmanazab has something to test :)

**Comment by dpryan79** [comment]
@bgruening Sounds like a plan, I'll see if I can get something together tomorrow.

**Comment by dpryan79** [comment]
We'll see if travis likes my PR , it seems to work locally at least :)
